version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pitstop
    ports: ["3306:3306"]
    command: ["--default-authentication-plugin=mysql_native_password","--lower_case_table_names=1"]
    volumes: [ "mysql_data:/var/lib/mysql" ]
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
  mysql_data:
